services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "platform"
      POSTGRES_USER: "fafafa"
      POSTGRES_PASSWORD: "Zze780m072VH"
    volumes:
      - /home/gost/pets/bntu-platform/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - platform-network
networks:
  platform-network:
    driver: bridge